### YamlMime:ManagedReference
apiRules:
- include: # The namespaces to generate
    uidRegex: ^Racer
    type: Namespace
- exclude:
    uidRegex: .* # Every other namespaces are ignored
    type: Namespace